-- SideQuest feedback storage for trusted server-side submissions.
-- Run this file manually in the Supabase SQL Editor.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  feedback_type text not null
    check (feedback_type in ('bug', 'idea', 'like', 'other')),
  rating integer
    check (rating between 1 and 5),
  message text not null
    check (char_length(btrim(message)) between 1 and 1000),
  page_path text
    check (
      page_path is null
      or (
        char_length(page_path) between 1 and 300
        and page_path like '/%'
      )
    ),
  created_at timestamptz not null default now()
);

create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);

create index if not exists feedback_user_id_idx
  on public.feedback (user_id)
  where user_id is not null;

alter table public.feedback enable row level security;

-- There are intentionally no policies for anon or authenticated roles:
-- they cannot read or mutate feedback through the public Supabase API.
revoke all on table public.feedback from anon, authenticated;
revoke all on sequence public.feedback_id_seq from anon, authenticated;

-- Only the trusted server-side Supabase client may create feedback records.
grant usage on schema public to service_role;
grant insert on table public.feedback to service_role;
grant usage, select on sequence public.feedback_id_seq to service_role;
